import React, { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';

export default function Example() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <Button variant="primary" onClick={handleShow}>
        Read Whitepaper
      </Button>

      <Modal show={show} onHide={handleClose} animation={true}>
        <Modal.Header closeButton>
        <Modal.Title>White Paper</Modal.Title>
        </Modal.Header>
        <Modal.Body>
        THE PRIMARY OBJECTIVE OF THIS TOKEN IS TOO DELIVER A LONG TERM CAPITAL GROWTH, THE TOKEN IS 
        SUITABLE FOR MEDIUM AND LONG TERM. THE STRAIGHTFORWARD, AND WELL INTEGRATED FLEXIBLE ECOSYSTEM IS 
        SUSTAINABLE WHILE ACHIEVING HIGHER TOKEN VALUES AND CAPITALIZED MARKET.

IN THE WORLD OF WEB3 AND THE CRYPTO CURRENCY WE HAVE ALOT OF OF GREAT PROJECT WITH DIFFERENT IDEAS AND THE WAY 
THE PROMOTE. TRAPCOIN WAS ACTUALLY FOUNDED MY A SMALL WEB3 FAMILY WITH GREAT LOVE FOR ONE ANOTHER. 
TRAP COIN ARE OUTLINE IN DIFFERENT CATEGORY IN THE CRYPTOCURRENCY AND THE WORLD OF NFTS. 

NFT COLLECTIONS. WE GONNA BE HAVING AN NFTS COLLECTION FOR TRAP COIN WORLD,MAKING KNOWN TO INVESTORS THERE 
COULD BE ALSO BE A HOLDERS OF NFTS PROJECT.

*PLAY TO EARN; GAMES TO HELP BUILD INVESTORS AND STAKE HOLDERS HAVE MORE BENEFICIAL FISCAL STRUCTURE ON THE
 CRYPTO CURRENCY

*TRAPCOIN TOKEN: OUR PLAN IS TO HAVE A STABLE COIN GROWTH AND ADD LIQUIDITY AND MAKING ALOT OF 
VERIFICATION TO THE TOKEN

BUILDING A CRYPTO WALLET: BUILDING A SUFFICIENT, EFFECTIVE AND SUFFICIENT IS PART OF WHAT WE ARE WORKING TO 
BE ABLE TO PASS OUT TRANSACTION TO DIFFERENT BLOCKCHAIN.

BLOCKCHAIN MARKETPLACE: HAVING THAT IS GOING TO BE PART OF OUR PLAN BUH WE WISH WE GONNA GET THAT DONE.
GETTING TO BUILD A MARKETPLACE FOR NFT ARTIST TO MINT,AND ALSO WITH THAT INVESTOR COULD ALSO BE PART OF THE NFT WORLD.

AIM OF TRAPCOIN

MOST CRYPTO FANS AND HOLDER'S HAVE NOT FULLY UNDERSTAND THE NFTS,WEB3 WORLD. SO WHAT TRAPCOIN PLANS TO DO IS
TO MERGE BOTH THE CRYPTO CURRENCY AND THE NFTS TOGETHER. HAVING THIS SAID IT GONNA BE HARD PROCESS BUH THE TEAM 
HAVE THIS CONVICTION WEB3, METAVERS, NFTS E.T.C CRYPTOCURRENCY SHOULD BE PLACE TOGETHER RELATIVE TO THE INVESTOR'S
HAVING THEM TRADES BETWEEN NFTS AND DIFFERENT CRYPTOCURRENCY. 

UTILITY

TRAPCOIN  ($TC) SERVE AS A ECOSYSTEM OF VALUE AND A MEANS OF EXCHANGE OF ALL TRAP COIN ($TC) STRUCTURE. 
THESE PRODUCTS INCLUDING GAMING PLAY TO EARN (P2E), NFTS e.t.c
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
      
        </Modal.Footer>
      </Modal>
    </>
  );
}

